# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Node
        uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      
      - name: Install dependencies
        run: npm install
        
      - name: Build App
        run: npm run build
      
      - name: Deploy
        uses: actions/checkout@v3
        with:
          repository: Dario-Felipe/whats-is-the-number
          folder: build
          branch: gh-pages
    
        
        


